1. Dizi kopyala
2. Diziye eleman ekleme ve silme
3. Boyut öğrenme ve şekil  değiştirme
4. Dizi yazdırma (döngülerlerle )
5. Hızlı dizi oluşturma (inspace ,zeros , ones , enty )
6.Rastgele sayılardan dizi oluşturma
7. Matematiksel işlemler
8. Koşula göre dizi belirleme
9.Dizileri birleştirme ve bölme *italik metin*

In [ ]:
import  numpy as np

1. Dizi kopyala


In [ ]:
d1 = np.array([1,2,3,4,5,6])
d2= d1.copy() #d1 değişirse değişir .
d3 = d1.view() #d1 değişirse değişmez.
print("Copy ile çoğaltılan None {0} döndürür .".format(d2.base))
print("view ile çoğaltılan  değer  {0} döndürür .".format(d2.base))




Copy ile çoğaltılan None None döndürür .
view ile çoğaltılan  değer  None döndürür .


In [ ]:
d1[0] =5 #d1 değişince
print("copy ile değiştirilen (0) değişmez".format(d2))
print("view ile değiştirilen (0) değişir".format(d3))


copy ile değiştirilen (0) değişmez
view ile değiştirilen (0) değişir


2 . Diziye eleman ekleme veya silme


In [ ]:
d4=np.array([1,2,3,4,5,6])
print(d4)

[1 2 3 4 5 6]


In [ ]:
# tek boyutlu diziye ekleme
d4 = np.append(d4, [7,8]) # sona ekler
# tek  boyutlu diziden silme
d4 = np.delete(d4, 2) # 2 nolu indeksten sil
print(d4)


[1 2 4 5 6 7 8]


In [ ]:
# çok boyutlu diziye eleman ekleme
d5 = np.array([ [1,2], [3,4] ])
print(d5)

In [ ]:
d5  = np.append(d5, [[5,6]] ,axis=0 ) # satır olarak ekler
print(d5)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
d6= np.array([[1,2,3],[4,5,6]])
print(d6)

[[1 2 3]
 [4 5 6]]


In [ ]:
d6 = np.append(d6, [[7] , [8]], axis=1) #sütun olarak ekler
print(d6)

[[1 2 3 7 7 7 7 7 7]
 [4 5 6 8 8 8 8 8 8]]


In [ ]:
# çok boyutlu dizi eleman silme
d7 = np.array([[1,2],[3,4],[5,6]])
print(d7)
print("***************")
d7 = np.delete(d7 , 1 , axis=0 ) #1 .satırı sil
print(d7)

[[1 2]
 [3 4]
 [5 6]]
***************
[[1 2]
 [5 6]]


In [ ]:
# çok boyutlu eleman dizi silme
d8 = np.array([[1,2] ,[3,4], [5,6]])
print(d8)

print("**************")
d8 = np.delete(d8 , 0, axis=1) # 1.sütunu sil
print(d8)

[[1 2]
 [3 4]
 [5 6]]
**************
[[2]
 [4]
 [6]]


3.Boyut ve şekil öğrenme

In [ ]:
# boyut (size) ve şekil (shape ) öğrenme
d9 = np.array([1,2,3,4,5,6,7,8])
print("dizi boyutu {0} ".format(d9.size))
print("dizi şekli {0} ".format(d9.shape))

dizi boyutu 8 
dizi şekli (8,) 


In [ ]:
#yeniden şekillendirme
d9.reshape(2,4) # 2×4 matris
print(d9) # değişmez

[1 2 3 4 5 6 7 8]


In [ ]:
d9 = d9.reshape(8,)
print(d9)

[1 2 3 4 5 6 7 8]


In [ ]:
d9 = d9.reshape(4,2)
print(d9)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# boyut değiştirme
d10 = np.array([1,2,3,4,5,6])
print("d10 dizisi {0} ve boyutu {1} ".format(d10,d10.size))

d10 dizisi [1 2 3 4 5 6] ve boyutu 6 


In [ ]:
d10 =np.resize(d10,(2,3))
print("d10 dizisi {0} ve boyutu {1}".format(d10,d10.size))

d10 dizisi [[1 2 3]
 [4 5 6]] ve boyutu 6


***reshape*** metodu diziyi yeniden boyutlamamızı  sağlar fakat  dizide  kalıcı değişiklik yapmaz , başka bir değişkende tutmamız gerekir . Dizide kalıcı şekilde bir boyut değişikliği yapılmak istendiğinde ***resize*** metodu kullanılabilir .

4 .Dizi yazdırma(döngülerle)

In [ ]:
d11= np.array([1,2,3,4,5,6])
for i in d11:
  print(i)

1
2
3
4
5
6


In [ ]:
d12 = np.array([[1,2,3],[4,5,6]])
for i in d12:
  for x in i:
    print(x)

1
2
3
4
5
6


For döngüsü yerine elemanları tek tek yazdımak yerine daha pratik bir yolu var .

In [ ]:
for i in np.nditer(d12)
  print(i)

SyntaxError: ignored

5 .Hızlı dizi oluşturma (linspace , arrange , zeros , one , emty)


In [ ]:
d13 = np.linspace(1,10,3) #1 den 10 a kadar 3 elemanlı bir dizi oluşturur .
print(d13)

[ 1.   5.5 10. ]


In [ ]:
d14 = np.arange(1,15,4) # 1 den  15 e kadar (15 dahil değil) 4 artarak bir dizi oluştur.
print(d14)

[ 1  5  9 13]


In [ ]:
d15 = np.zeros((2,3))  # 0 değerlerinden oluşan 2×3 lü bir dizi
print(d15)

NameError: ignored

In [ ]:
d16 = np.ones((3,2)) # 1 değerlerinden oluşan 3×2 bir dizi
print(d16)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
d17 = np.empty((4,4)) #boş değerlerden oluşan oluşan (aslında boş değil) 4×4  bir dizi oluşturur .
print(d17)

[[2.33095271e-316 0.00000000e+000 2.41907520e-312 2.37663529e-312]
 [2.22809558e-312 2.46151512e-312 6.79038654e-313 2.35541533e-312]
 [2.46151512e-312 6.79038654e-313 2.35541533e-312 6.79038654e-313]
 [2.14321575e-312 2.22809558e-312 2.14321575e-312 2.25064900e-153]]


6 . Rastgele sayılaradn oluşan dizi oluşturma


In [ ]:
r1 = np.random.rand(3,4) # 3×4 rastgele bir dizi
print(r1)

In [ ]:
r2 = np.random.randn(3,2) # 3×2 rastgele normal dağılımlı dizi
print(r2)

[[ 1.23465273 -0.51560421]
 [-1.50090355 -0.17143376]
 [ 1.66085254  0.82758133]]


In [ ]:
r4  = np.random.randint(0,10,(4,4)) # 1 ile 10 arasında int türünde 4×4 bir dizi
print(r4)

7 .matematiksel işlemler

In [ ]:
m1 = np.array([1,2,3])
m2 = np.array([4,5,6])
print(m1)
print(m2)

[1 2 3]
[4 5 6]


In [ ]:
to = m1 +m2
cı = m1-m2
car = m1*m2
bol = m1/m2
print(" m1 ve m2 toplamı {0} Farkı {1} ,Çarpan {2} Bölme {3}".format(to,cı,car,bol)  )

 m1 ve m2 toplamı [5 7 9] Farkı [-3 -3 -3] ,Çarpan [ 4 10 18] Bölme [0.25 0.4  0.5 ]


In [ ]:
kk = np.sqrt(m1)
kup = np.power(m1 ,3)
ort = np.mean(m1)
med = np.median(m1)
print("m1 ;  karekök {0} küp{1} , ortalama {2} , median {3}".format(kk,kup,ort,med))

m1 ;  karekök [1.         1.41421356 1.73205081] küp[ 1  8 27] , ortalama 2.0 , median 2.0


8 .Koşula göre dizi birleştirme

In [ ]:
dz1  = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(dz1[(dz1>-1) & (dz1<5)])
print(dz1[(dz1<3) | (dz1>7)])
print(dz1[((dz1<3) | (dz1>7) ) &  ((dz1> -1)&(dz1<11))])

In [ ]:
dz1[dz1%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

9 :Dizileri birleştirme ve bölme

In [ ]:
a = np.array([[1,2,3] , [4,5,6]])
b= np.array([[7,8,9] ,[10,11,12]])
c= np.concatenate((a,b) ,axis=0) # satırda birleştir alt alta
d= np.concatenate((a,b), axis=1) # sütunda birleştir yan yana
print(c)
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
e = np.array([1,2,3,4,5,6,7,8])
f = np.split(e,2,axis=0)
print(f)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [ ]:
e = np.array([[1,2,3,4] , [5,6,7,8]])
f= np.split(e,2,axis=1)
print(e)
print(f)

[[1 2 3 4]
 [5 6 7 8]]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
